import React from "react";
import { useLanguage } from "../contexts/LanguageContext";

export default function PrivacyPolicyPage() {
  const { language } = useLanguage();
  const isDE = language === "de";

  return (
    <div className="max-w-3xl mx-auto px-5 py-16 text-left font-sans">
      <h1 className="font-serif text-3xl font-bold text-brand-navy mb-2">
        {isDE ? "Datenschutzerklärung" : "Privacy Policy"}
      </h1>
      <p className="text-xs text-gray-400 mb-10">{isDE ? "Stand: Juni 2025" : "Last updated: June 2025"}</p>

      <div className="space-y-8 text-sm text-gray-700 leading-relaxed">

        <section>
          <h2 className="font-semibold text-brand-navy text-base mb-2">{isDE ? "1. Verantwortlicher" : "1. Data Controller"}</h2>
          <p>
            Constantin Nixdorff<br />
            [ADDRESS — bitte vor Veröffentlichung ergänzen]<br />
            E-Mail: <a href="mailto:constantin.nixdorff@mlp.de" className="text-brand-gold hover:underline">constantin.nixdorff@mlp.de</a>
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-brand-navy text-base mb-2">{isDE ? "2. Erhobene Daten & Zweck" : "2. Data Collected & Purpose"}</h2>
          <div className="space-y-4">
            <div>
              <h3 className="font-medium text-brand-navy mb-1">{isDE ? "Kontaktformular" : "Contact Form"}</h3>
              <p>
                {isDE
                  ? "Wenn Sie unser Kontaktformular nutzen, erheben wir folgende Daten: Name, E-Mail-Adresse, Telefonnummer, Beratungsanliegen und Firmenname (optional). Diese Daten werden ausschließlich zur Bearbeitung Ihrer Anfrage und zur Kontaktaufnahme verwendet. Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO (Vertragsanbahnung)."
                  : "When you use our contact form, we collect: name, email address, phone number, consultation request, and company name (optional). This data is used solely to process your enquiry. Legal basis: Art. 6(1)(b) GDPR (pre-contractual measures)."}
              </p>
            </div>
            <div>
              <h3 className="font-medium text-brand-navy mb-1">{isDE ? "Chat-Assistent" : "Chat Assistant"}</h3>
              <p>
                {isDE
                  ? "Der Chat-Assistent auf dieser Website ist ein automatisiertes System (kein Mensch). Nachrichten, die Sie eingeben, werden zur Beantwortung Ihrer Fragen verarbeitet und nicht dauerhaft gespeichert. Rechtsgrundlage: Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an der Bereitstellung des Dienstes)."
                  : "The chat assistant on this website is an automated system (not a human). Messages you enter are processed to answer your questions and are not stored permanently. Legal basis: Art. 6(1)(f) GDPR (legitimate interest in providing the service)."}
              </p>
            </div>
            <div>
              <h3 className="font-medium text-brand-navy mb-1">Google Analytics</h3>
              <p>
                {isDE
                  ? "Mit Ihrer Einwilligung verwenden wir Google Analytics 4 (Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland) zur Analyse der Website-Nutzung. Dabei wird Ihre IP-Adresse anonymisiert. Die durch Cookies erzeugten Informationen werden auf Servern von Google in der EU verarbeitet. Sie können Ihre Einwilligung jederzeit widerrufen. Rechtsgrundlage: Art. 6 Abs. 1 lit. a DSGVO (Einwilligung)."
                  : "With your consent, we use Google Analytics 4 (Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland) to analyse website usage. Your IP address is anonymised. Information generated by cookies is processed on Google's servers in the EU. You can withdraw your consent at any time. Legal basis: Art. 6(1)(a) GDPR (consent)."}
              </p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="font-semibold text-brand-navy text-base mb-2">{isDE ? "3. Cookies" : "3. Cookies"}</h2>
          <p>
            {isDE
              ? "Wir verwenden technisch notwendige Cookies (z. B. zur Speicherung Ihrer Cookie-Einstellungen) sowie – nach Ihrer Einwilligung – Analyse-Cookies (Google Analytics). Sie können Ihre Einwilligung jederzeit durch Löschen der Browser-Cookies widerrufen."
              : "We use technically necessary cookies (e.g. to store your cookie preferences) and — upon your consent — analytics cookies (Google Analytics). You can withdraw consent at any time by clearing your browser cookies."}
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-brand-navy text-base mb-2">{isDE ? "4. Speicherdauer" : "4. Retention Period"}</h2>
          <p>
            {isDE
              ? "Kontaktformular-Daten werden für maximal 6 Monate gespeichert, sofern kein Vertragsverhältnis entsteht. Google Analytics-Daten werden nach 14 Monaten automatisch gelöscht."
              : "Contact form data is stored for a maximum of 6 months unless a contractual relationship is established. Google Analytics data is automatically deleted after 14 months."}
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-brand-navy text-base mb-2">{isDE ? "5. Ihre Rechte" : "5. Your Rights"}</h2>
          <p className="mb-2">
            {isDE
              ? "Sie haben das Recht auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung der Verarbeitung (Art. 18), Datenübertragbarkeit (Art. 20) und Widerspruch (Art. 21 DSGVO)."
              : "You have the right to access (Art. 15 GDPR), rectification (Art. 16), erasure (Art. 17), restriction of processing (Art. 18), data portability (Art. 20), and objection (Art. 21 GDPR)."}
          </p>
          <p>
            {isDE
              ? "Zur Ausübung Ihrer Rechte wenden Sie sich bitte an: "
              : "To exercise your rights, please contact: "}
            <a href="mailto:constantin.nixdorff@mlp.de" className="text-brand-gold hover:underline">constantin.nixdorff@mlp.de</a>
          </p>
          <p className="mt-2">
            {isDE
              ? "Sie haben außerdem das Recht, sich bei der zuständigen Datenschutzaufsichtsbehörde zu beschweren."
              : "You also have the right to lodge a complaint with the competent data protection supervisory authority."}
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-brand-navy text-base mb-2">{isDE ? "6. Datensicherheit" : "6. Data Security"}</h2>
          <p>
            {isDE
              ? "Diese Website verwendet SSL/TLS-Verschlüsselung für alle Datenübertragungen. Unbefugter Zugriff durch Dritte wird durch technische und organisatorische Maßnahmen verhindert."
              : "This website uses SSL/TLS encryption for all data transmissions. Unauthorised access by third parties is prevented through technical and organisational measures."}
          </p>
        </section>

      </div>
    </div>
  );
}
